crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vizit.urls')), 
    path('__debug__/', include('debug_toolbar.urls')),
]
admin.site.site_header = 'Учет визитов.'
admin.site.site_title = 'Учет визитов.'

crm/vizit/urls.py
from django.urls import path,include 
from .views import *
 
app_name = 'Vizit'
urlpatterns = [
    path('', index, name='home'),
     
    path('contactauto/', ContactAutocomplete.as_view(), name='ContactAuto'),
    path("accounts/", include("django.contrib.auth.urls")),  

    path('hintwork/', gethint, name='hintwork'),

    path("visits/", VisitList.as_view(), name='VisitList'),
    path('visit/<pk>/', VizitUpdate.as_view(), name='VisitEdit'),
    path('visit/<pk>/delete/', VizitDelete.as_view(), name='VisitDelete'),
    path("visitadd", VizitCreate.as_view(), name='VisitAdd'),
        
    path('contact/<pk>', ContactUpdate.as_view(), name='ContactEdit'),
    path("contacts/", ContactList.as_view(), name='ContactList'),
    path("contactadd/", ContactCreate.as_view(), name='ContactAdd'),
    path("reports/kpi", ReportKpi, name='ReportKpi'),
    path("reports/cont", export_excel_vrach, name='ReportContact'),
    
    path("exp", export_excel, name='export_excel'),
    path("activity", ShowActivity.as_view(), name='show_activity'),
    path("exp_kpi", export_excel_kpi, name='export_excel_kpi'),
    path("exp_event", export_excel_events, name='export_excel_events'),
    path("exp_event_short", export_excel_events_short, name='export_excel_events'),

    path("initfreq", initinsert, name='initinsert'),
    
    #path("destroy", deletecontactlist, name='delcontactlist'),
    
    path("events", EventList.as_view(), name='EventList'),
    path('eventadd', EventCreateView.as_view(), name='EventCreate'),
    path('event/<pk>', EventUpdateView.as_view(), name='EventUpdate'),
    
    path('test', TestView.as_view(), name='EventUpdate'),
]

crm/vizit/models.py
from django.db import models

# Create your models here.

class Vizit(models.Model):

    result_choise=[('Cold', 'Cold'),('Warm', 'Warm'),('Hot', 'Hot')]
    type_choise= [('К специалисту', 'К специалисту'),('Follow-up визит', 'Follow-up визит'),('Телефонный визит', 'Телефонный визит')]
    status_choise= [('Открыт', 'Открыт'),('Закрыт', 'Закрыт')]

    viztype = models.CharField(max_length=20, verbose_name='Тип визита', choices=type_choise)
    vizstatus = models.CharField(max_length=20, verbose_name='Статус', choices=status_choise, default='Открыт')
    datenext = models.DateTimeField(blank=True,null=True, db_index = True, verbose_name='Дата следующего визита')
    datefact = models.DateTimeField(auto_now_add = False, db_index = True, verbose_name='Дата визита')
    goal = models.CharField (max_length=200, db_index=True, verbose_name='Цель визита')
    nextaction = models.CharField (blank=True,null=True, max_length=200, db_index=True, verbose_name='Дальнейшие действия с клиентом')
    social_link = models.BooleanField (blank=True, null = True, verbose_name='Подписание клиента на соцсети')
    result = models.CharField(blank=True, null=True, max_length=10, verbose_name='Результат визита (личная оценка)', choices=result_choise)
    contact = models.ForeignKey ('Contact', null = True, on_delete=models.PROTECT, verbose_name='Контакт')
    comment  = models.TextField(blank=True, null=True,  verbose_name='Комментарий')
    kamid = models.ForeignKey('Kam',on_delete=models.PROTECT, verbose_name='Сотрудник')
    hint_organization = models.CharField (blank=True, null = True, max_length=200, db_index=True, verbose_name='Место работы')
    hint_special = models.CharField (blank=True, null = True, max_length=200, db_index=True, verbose_name='Специальность')
    datecreate = models.DateTimeField(auto_now_add = True, db_index = True, verbose_name='Дата создания')

    class Meta:
        verbose_name_plural = 'Визиты'
        verbose_name = 'Визит'
    
    def __str__(self) -> str:
        return self.kamid.name + ' ' + self.viztype


class Kam(models.Model):
    name  = models.CharField(max_length=250, verbose_name='Фио сотрудника')
    siteuser = models.CharField(max_length=250, verbose_name='Логин на сайте')

    class Meta:
        verbose_name_plural = 'Сотрудники'
        verbose_name = 'Сотрудник'
    
    def __str__(self) -> str:
        return self.name 

class Contact(models.Model):
    cat1=[('A', 'A'),('B', 'B'),('C', 'C'),('D', 'D')]
    cat2=[('0', '0'),('1', '1'),('2', '2'),('3', '3')]
    cat3=[('L-D', 'L-D'),('LOW', 'LOW'),('MID', 'MID'),('TOP', 'TOP')]
    cat4=[('LD', 'LD'),('LOW', 'LOW'),('MID', 'MID'),('TOP', 'TOP')]
    
    special = [
    ('дерматолог-косметолог','дерматолог-косметолог'),
    ('пластический хирург','пластический хирург'),
    ('Администратор','Администратор'), 
    ('Другое','Другое'),
    ('Гл.врач','Гл.врач')
    ]

    name  = models.CharField(max_length=250, verbose_name='Фио врача')
    spec  = models.CharField(max_length=250, verbose_name='Специальность', choices=special)
    phone = models.CharField(null=True, blank = True, max_length=250, verbose_name='Телефон')
    email = models.CharField(null=True, blank = True, max_length=250, verbose_name='Email')
    
    category_account = models.CharField(null=True, blank = True,max_length=12, verbose_name='Account Cat', choices=cat1)
    category_restylane = models.CharField(null=True, blank = True,max_length=12, verbose_name='Restylane loyalty', choices=cat2)
    category_sculptra = models.CharField(null=True, blank = True,max_length=12, verbose_name='Sculptra Cat', choices=cat3)
    
    cat_filler_potencial =models.CharField(null=True, blank = True,max_length=12, verbose_name='Fillers Category Potencial', choices=cat1)
    cat_filler_loyalty =models.CharField(null=True, blank = True,max_length=12, verbose_name='Fillers Loyalty', choices=cat2)

    cat_biostim_potencial =models.CharField(null=True, blank = True,max_length=12, verbose_name='Biostimulators Category Potential', choices=cat4)
    cat_biostim_loyalty =models.CharField(null=True, blank = True,max_length=12, verbose_name='Biostimulators Loyalty', choices=cat2)

    cat_idp_potencial =models.CharField(null=True, blank = True,max_length=12, verbose_name='IDP Category', choices=cat1)
    cat_idp_loyalty =models.CharField(null=True, blank = True,max_length=12, verbose_name='IDP Loyalty', choices=cat2)


    city   = models.CharField(max_length=250, verbose_name='Город')
    kam = models.ForeignKey ('Kam', null = True, on_delete=models.PROTECT, verbose_name='КАМ')
    work_place = models.CharField(max_length=250, verbose_name='Место работы')
    comment = models.CharField(null=True, blank = True, max_length=250, verbose_name='Комментарий')
    name_dashboard = models.CharField(null=True, blank = True, max_length=250, verbose_name='Наименование в DB')
    date_create = models.DateTimeField(auto_now_add = True, verbose_name='Дата создания')
    deleted = models.BooleanField(default=False, verbose_name='Контакт удален')

    def category(self):
        res =""
        if self.cat_filler_potencial is not None:
            res+= self.cat_filler_potencial 
        if self.cat_filler_loyalty is not None:
            res+= self.cat_filler_loyalty

        if self.cat_biostim_potencial is not None:
            res+= self.cat_biostim_potencial 
        if self.cat_biostim_loyalty is not None:
            res+= self.cat_biostim_loyalty 

        if self.cat_idp_potencial is not None:
            res+= self.cat_idp_potencial 
        if self.cat_idp_loyalty is not None:
            res+= self.cat_idp_loyalty 
        
        return res
        
    
    def __str__(self) -> str:
        return self.name       

    class Meta:
        verbose_name_plural = 'Контакты'
        verbose_name = 'Контакт'

class VizitFreq(models.Model):
    year=models.IntegerField(verbose_name="Год")
    month=models.IntegerField(verbose_name="Месяц")
    kamid = models.ForeignKey ('Kam', null = True, on_delete=models.PROTECT, verbose_name='КАМ')
    workdays=models.IntegerField(verbose_name="Дней в месяце",null=True, blank = True)
    dayoff_minus=models.IntegerField(verbose_name="Выходные",null=True, blank = True)
    dayadm_minus=models.FloatField(verbose_name="Адм. работа",null=True, blank = True)
    workday_count=models.FloatField(verbose_name="Дней работы",null=True, blank = True)
    contact_count_a=models.IntegerField(verbose_name="Колво врачей А",null=True, blank = True)
    contact_count_b=models.IntegerField(verbose_name="Колво врачей B",null=True, blank = True)
    contact_count_c=models.IntegerField(verbose_name="Колво врачей C",null=True, blank = True)
    plan_count_a=models.IntegerField(verbose_name="План визитов А",null=True, blank = True)
    plan_count_b=models.IntegerField(verbose_name="План визитов B",null=True, blank = True)
    plan_count_c=models.IntegerField(verbose_name="План визитов C",null=True, blank = True)
    freq_a=models.FloatField(verbose_name="Частота А",null=True, blank = True)
    freq_b=models.FloatField(verbose_name="Частота B",null=True, blank = True)
    freq_c=models.FloatField(verbose_name="Частота C",null=True, blank = True)
    freq_total=models.FloatField(verbose_name="Частота C",null=True, blank = True)
    kamname  = models.CharField(max_length=250, verbose_name='Фио kam',null=True, blank = True)
    fact_count_a=models.IntegerField(verbose_name="Факт визитов А",null=True, blank = True)
    fact_count_b=models.IntegerField(verbose_name="Факт визитов B",null=True, blank = True)
    fact_count_c=models.IntegerField(verbose_name="Факт визитов C",null=True, blank = True)
    
    procent_a=models.FloatField(verbose_name="% А",null=True, blank = True)
    procent_b=models.FloatField(verbose_name="% B",null=True, blank = True)
    procent_c=models.FloatField(verbose_name="% C",null=True, blank = True)
    
    def __str__(self) -> str:
        return str(self.month) +'/'+ str(self.year) +'/'+ self.kamname + ' ID строки:' + str(self.pk) 
    
    class Meta:
        verbose_name_plural = 'Частота визитов'
        verbose_name = 'Частота визитов'

class Event(models.Model):

    kamid = models.ForeignKey(Kam,on_delete=models.PROTECT, verbose_name='Сотрудник')
    dateevent = models.DateTimeField(auto_now_add = False, db_index = True, verbose_name='Дата мероприятия')
    
    topic = models.ForeignKey ('EventTopic', on_delete=models.PROTECT,db_index=True, verbose_name='Тема мероприятия')
    result = models.CharField(blank=True, null=True, max_length=255, verbose_name='Результат')
    goal = models.CharField(blank=True, null=True, max_length=255, verbose_name='Цель')
    city = models.CharField(blank=True, null=True, max_length=255, verbose_name='Город')

    class Meta:
        verbose_name_plural = 'Мероприятие'
        verbose_name = 'Мероприятия'
    
class EventTopic(models.Model):
    topicname = models.CharField (max_length=200, db_index=True, verbose_name='Тема мероприятия')
    
    def __str__(self) -> str:
        return self.topicname   

    class Meta:
        verbose_name_plural = 'Тема мероприятия'
        verbose_name = 'Темы мероприятий'


class EventMember(models.Model):
    parentevent = models.ForeignKey(Event, on_delete=models.CASCADE)
    contact = models.ForeignKey (Contact, null = True, on_delete=models.PROTECT, verbose_name='Контакт')
    
    class Meta:
        verbose_name = 'Участник мероприятия'
        verbose_name_plural = 'Участники мероприятия'

crm/vizit/forms.py
from django.forms.models import BaseInlineFormSet
from django.forms.models import inlineformset_factory
from django.forms import ModelForm
from django.forms.widgets import *
from .models import *
from django import forms
from dal import autocomplete

class VizitForm(ModelForm): 
        
    result_choise=[('Cold', 'Cold'),('Warm', 'Warm'),('Hot', 'Hot')]
    contact_choise= [('0','---')]
    datefact = forms.DateTimeField(widget =DateTimeInput(), label='Дата визита')
    datenext = forms.DateTimeField(required=False, widget =DateTimeInput(), label='Дата следующего визита')
    result= forms.ChoiceField(choices=result_choise,widget=forms.RadioSelect(), label='Результат визита (личная оценка)')
    hint_organization = forms.CharField(label ='Место работы', widget=forms.TextInput(attrs={'style': 'pointer-events: none;'}),required=False)
    hint_special = forms.CharField(label ='Специальность', widget=forms.TextInput(attrs={'style': 'pointer-events: none;'}),required=False)
    
    
    #contact  = forms.CharField(required=False,widget=autocomplete.ModelSelect2(url='Vizit:ContactAuto'))
    class Meta:
        model=Vizit
        fields =  ['kamid','vizstatus','contact','hint_organization','hint_special',"goal",'viztype',"datefact",'result',"datenext",'social_link','nextaction','comment']
        
        widgets = {
            #'contact': autocomplete.ModelSelect2(url='Vizit:ContactAuto'),
            'comment': Textarea(attrs={'cols': 80, 'rows': 3}),
            
            } 


    def __init__(self, *args, **kwargs):
        """ Grants access to the request object so that only members of the current user
        are given as options"""

        self.request = kwargs.pop('request')
        super(VizitForm, self).__init__(*args, **kwargs)
        kams  = Kam.objects.filter(siteuser=self.request.user)
        if kams:
            kamid = kams[0].pk
            self.fields['contact'].queryset = Contact.objects.filter(kam=kamid, deleted=False ).order_by('name')
        else:
            self.fields['contact'].queryset = Contact.objects.filter(kam=-999)
    

MemberFormset = inlineformset_factory(Event,EventMember, fields = '__all__',extra=5,widgets={'contact': autocomplete.ModelSelect2(url='Vizit:ContactAuto')})

class EventForm(ModelForm): 
        
    inf = '%Y/%m/%d %H:%M'
    print(inf)
    dateevent = forms.DateTimeField(required=False, widget =DateTimeInput(),  label='Дата')

        
    #contact  = forms.CharField(required=False,widget=autocomplete.ModelSelect2(url='Vizit:ContactAuto'))
    class Meta:
        model=Event
        fields = ["dateevent", "goal", "result","kamid","topic"]

crm/vizit/templates/vizit/contact_form.html
{% extends "layout/base.html" %}
{% load static %}


{% block content %}
<h4>Редактирование контакта</h4>

<form action="" method="post" enctype= "multipart/form-data">

    {% csrf_token %}
	<table style="width: 100%;">
    <colgroup>
      <col span="1" style="width: 20%;">
      <col span="1" style="width: 80%;">
      
   </colgroup>
   
    {{form.as_table }}
	</table>
    <input type="submit" value="Сохранить">

</form>


{%endblock%}

crm/vizit/templates/vizit/contact_list.html
{% extends "layout/base.html" %}
{% load static %}


{% block content %}
<h4>Список контактов</h4>

<form method="get">
    
    {% csrf_token %}


        <p> Kam 
        <select name="kamid" class="filter">
            <option value="" selected>Все</option>
          
            <option value="1">Жанна</option>
            <option value="2">Наталья</option>
            <option value="3">Анастасия</option>
            <option value="5">Москва</option>
            <option value="7">Мария</option>
            <option value="8">Наталья</option>
            <option value="9">Дарья</option>
            <option value="11">Светлана</option>
          
          </select>
        </p> 


    <p> Категория врача
    <select name="category_account" class="filter">
        <option value="" selected>Все</option>
      
        <option value="A">A</option>
      
        <option value="B">B</option>
      
        <option value="C">C</option>
      
        <option value="D">D</option>
      
      </select>
    </p>

    <p>Поиск по ФИО <input name="fio" type="text" class="filter"/></p>
    <p><input type="submit" name="Применить фильтр" value="Применить фильтр"/></p>
</form>


<div id="visit list">
    <table width = "100%">
        <thead>
            <tr>
        <th>ФИО контакта</th>
        <th>Специальность</th>
        <th>Категория</th>
        <th>КАМ</th>
        <th>Дата создания</th>
            </tr>
        </thead>
        <tbody>
            {% for n in Contact %}
            <tr>
            <td> <a href="{% url 'Vizit:ContactEdit' n.id %}">  {{ n.name }} </a> </td>
            <td>  {{ n.spec }}  </td>
            <td> <a href="{% url 'Vizit:ContactEdit' n.id %}">  {{ n.category }} </a> </td>
            <td>  {{ n.kam }}  </td>
            <td>  {{ n.date_create }}  </td>

            </tr>
            {% endfor %}
            
        </tbody>
    </table>


</div>
<div class="pagination" style="margin:1em;">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a style="margin:1em" href="?page=1">&laquo; Первая </a>
            <a style="margin:1em" href="?page={{ page_obj.previous_page_number }}"> Предыдущая </a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a style="margin:1em" href="?page={{ page_obj.next_page_number }}"> Следующая</a>
            <a style="margin:1em" href="?page={{ page_obj.paginator.num_pages }}"> Последняя &raquo; </a>
        {% endif %}
    </span>
</div>

{%endblock%}

crm/vizit/templates/vizit/event_form.html
{% extends "layout/base.html" %}
{% load static %}
{% block content %}

<h4>Редактирование События</h4>

<form method="post" enctype="multipart/form-data">{% csrf_token %}

    {{ form.non_field_errors }}
    <table>
    {{ form.as_table }}
    </table>

    <h4>Участники</h4>

    {{ children.management_form }}
    {% for form in children %}

    <div class="inline">
    {% for field in form %}

        {{ field }}


    {% endfor %}

    </div>
    {% endfor %}

    <input type="submit" value="Save">
</form>



<script>
    $(function () {
      $("#id_dateevent").datetimepicker({
        format:'Y-m-d H:m',
        allowTimes:[
    '08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', 
    '16:00','17:00', '18:00'
    ],
      }

      );
      
    });
  </script>

{%endblock%}

crm/vizit/templates/vizit/event_list.html
{% extends "layout/base.html" %}
{% load static %}


{% block content %}
<h4>Список мероприятий</h4>

<form method="get">
    
    {% csrf_token %}


        <p> Kam 
        <select name="kamid" class="filter">
            <option value="" selected>Все</option>
          
            <option value="1">Жанна</option>
            <option value="2">Наталья</option>
            <option value="3">Анастасия</option>
            <option value="5">Москва</option>
            <option value="7">Мария</option>
            <option value="8">Наталья</option>
            <option value="9">Дарья</option>
            <option value="11">Светлана</option>
          
          </select>
        </p> 



   
    <p><input type="submit" name="Применить фильтр" value="Применить фильтр"/></p>
</form>


<div id="event list">
    <table width = "100%">
        <thead>
            <tr>
        <th>КАМ</th>
        <th>Город</th>
        <th>Тема</th>
        <th>Дата </th>
            </tr>
        </thead>
        <tbody>
            {% for n in Event %}
            <tr>
            <td> <a href="{% url 'Vizit:EventUpdate' n.id %}">  {{ n.kamid }} </a> </td>
            <td>  {{ n.city }}  </td>
            <td> <a href="{% url 'Vizit:EventUpdate' n.id %}">  {{ n.topic }} </a> </td>
            <td>  {{ n.dateevent }}  </td>

            </tr>
            {% endfor %}
            
        </tbody>
    </table>


</div>
<div class="pagination" style="margin:1em;">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a style="margin:1em" href="?page=1">&laquo; Первая </a>
            <a style="margin:1em" href="?page={{ page_obj.previous_page_number }}"> Предыдущая </a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a style="margin:1em" href="?page={{ page_obj.next_page_number }}"> Следующая</a>
            <a style="margin:1em" href="?page={{ page_obj.paginator.num_pages }}"> Последняя &raquo; </a>
        {% endif %}
    </span>
</div>
<br>
<p><a href="/exp_event" aria-current="page">Выгрузить в Excel мероприятия и их участников </a>  </p>
<p><a href="/exp_event_short" aria-current="page">Выгрузить в Excel мероприятия (краткий список) </a>  Эта выгрузка занимает 1-2 минуты. Подождите формирования файла. </p>

{%endblock%}

crm/vizit/templates/vizit/home.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}
<h2>Система учета визитов</h2>

<p>Добавлены мероприятия для тестирования. Можно пробовать добавлять. Потом вся часть мероприятий будет очищена</p>
<p>При необходимости добавить больше врачей - заново откройте страницу мероприятия, внизу добавятся строки. </p>


{% endblock content %}

crm/vizit/templates/vizit/test.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Static Example</title>

  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- XDSoft DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
</head>
<body>

  <input id="datetimepicker" type="text">

  <script>
    $(function () {
      $("#datetimepicker").datetimepicker();
    });
  </script>

</body>
</html>

crm/vizit/templates/vizit/vizit_activity.html
{% extends "layout/base.html" %}
{% load static %}


{% block content %}
<h4>Последние занесенные визиты</h4>

<div id="visit list">
    <table width = "100%">
        <thead>
            <tr>
        <th>Kam</th>
        <th>Тип визита</th>
        <th>Организация</th>
        <th>Контакт</th>
        <th>Дата создания</th>
        <th>Статус визита</th>
            </tr>
        </thead>
        <tbody>
            {% for n in Vizit %}
            
            <tr>
            <td> <a href="{% url 'Vizit:VisitEdit' n.id %}">  {{ n.kamid }} </a> </td>
            <td> <a href="{% url 'Vizit:VisitEdit' n.id %}">  {{ n.viztype }} </a> </td>
            <td>  {{ n.hint_organization }}  </td>
            <td> <a href="{% url 'Vizit:VisitEdit' n.id %}">  {{ n.contact }} </a> </td>
            <td>  {{ n.datecreate }}  </td>
            <td>  {{ n.vizstatus }}  </td>

            </tr>
            {% endfor %}
            
        </tbody>
    </table>


</div>


{%endblock%}

crm/vizit/templates/vizit/vizit_confirm_delete.html
{% extends "layout/base.html" %}
{% load static %}


{% block content %}
<h4>Удаление визита</h4>

<form action="" method="post" enctype= "multipart/form-data">

    {% csrf_token %}

    <p>Тип визита: {{ delcontact.viztype }}</p>
    <p>Дата визита: {{ delcontact.datefact }}</p>
    <p>Кам: {{ delcontact.kamid }}</p>

    <div class="submit-row">
    <input type="submit" value="Удалить визит">
    </div>
</form>

{%endblock%}

crm/vizit/templates/vizit/vizit_form.html
{% extends "layout/base.html" %}
{% load static %}


{% block content %}
<h4>Редактирование визита</h4>

<form action="" method="post" enctype= "multipart/form-data">

    {% csrf_token %}

  {{info_sended}}
	<table style="width: 100%;">
    <colgroup>
      <col span="1" style="width: 20%;">
      <col span="1" style="width: 80%;">
      
   </colgroup>
   
    {{form.as_table }}
	</table>
    <div class="submit-row">
    <input type="submit" value="Сохранить">
    {% if updatemode %}
     <a href="{% url 'Vizit:VisitDelete' object.pk %}" class="deletelink">Удалить</a>
    
    {% endif %}
    </div>
</form>

<script>
    $(function () {
      $("#id_datefact").datetimepicker({
        format:'Y-m-d H:m',
        allowTimes:[
    '08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', 
    '16:00','17:00', '18:00'
    ],
      }

      );
      
    });
  </script>

<script src="{% static 'vizit/hint.js' %}"></script>
{%endblock%}

crm/vizit/templates/vizit/vizit_list.html
{% extends "layout/base.html" %}
{% load static %}


{% block content %}
<h4>Список визитов</h4>


<form method="get">
    
    {% csrf_token %}
    <p> Kam 
        <select name="kamid" class="filter">
            <option value="" selected>Все</option>
          
            <option value="1">Жанна</option>
            <option value="2">Наталья</option>
            <option value="3">Анастасия</option>
            <option value="5">Москва</option>
            <option value="7">Мария</option>
            <option value="8">Наталья</option>
            <option value="9">Дарья</option>
            <option value="11">Светлана</option>

          </select>
        </p>    
        

    <p> Категория врача
    <select name="category_account" class="filter">
        <option value="" selected>Все</option>
      
        <option value="A">A</option>
      
        <option value="B">B</option>
      
        <option value="C">C</option>
      
        <option value="D">D</option>
      
      </select>
    </p>

    <p> Статус визита
        <select name="vizit_status" class="filter">
            <option value="" selected>Все</option>
          
            <option value="Закрыт">Закрыт</option>
          
            <option value="Открыт">Открыт</option>
          
          </select>
        </p>

    <p><input type="submit" name="Применить фильтр" value="Применить фильтр"/></p>
</form>


<div id="visit list">
    <table width = "100%">
        <thead>
            <tr>
        <th>Kam</th>
        <th>Тип визита</th>
        <th>Организация</th>
        <th>Контакт</th>
        <th>Дата визита</th>
        <th>Статус визита</th>
            </tr>
        </thead>
        <tbody>
            {% for n in Vizit %}
            
            <tr>
            <td> <a href="{% url 'Vizit:VisitEdit' n.id %}">  {{ n.kamid }} </a> </td>
            <td> <a href="{% url 'Vizit:VisitEdit' n.id %}">  {{ n.viztype }} </a> </td>
            <td>  {{ n.hint_organization }}  </td>
            <td> <a href="{% url 'Vizit:VisitEdit' n.id %}">  {{ n.contact }} </a> </td>
            <td>  {{ n.datefact }}  </td>
            <td>  {{ n.vizstatus }}  </td>

            </tr>
            {% endfor %}
            
        </tbody>
    </table>


</div>

<div class="pagination" style="margin:1em;">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a style="margin:1em" href="?page=1">&laquo Первая </a>
            <a style="margin:1em" href="?page={{ page_obj.previous_page_number }}"> Предыдущая </a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a style="margin:1em" href="?page={{ page_obj.next_page_number }}"> Следующая</a>
            <a style="margin:1em" href="?page={{ page_obj.paginator.num_pages }}"> Последняя &raquo; </a>
        {% endif %}
    </span>
</div>


{%endblock%}